name: conkit
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - scipy
  - pandas
  - matplotlib
  - cython
  - joblib
  - scikit-learn>=1.0
  - prettytable
  - biopython>=1.85
  - pip
  - pip:
    - -e .
